datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/catalog_service_db
  username: user76584930yr
  password: pasSw0rD6239ej
  schema: catalog_schema
liquibase:
  change-log: db/changelog/db.changelog-master.xml
  schema: liquibase_schema
  contexts: dev
redis:
  host: localhost
  port: 6379
  password: pasSw0Rd
  database: 0
  timeout: 2000
  cache:
    ttl:
      minutes: 30